name: "Request: Azure"
description: "Request for change on application hosted on Azure or Azure Infrastructure"
title: "Request: Azure - REQUEST_DESCRIPTION"
labels: ["account: azure","needs: triage","status: pending"]
assignees:
  - yashghia
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a brief description and justification of modifications being requested
    validations:
      required: true
  - type: textarea
    id: additionalContext
    attributes:
      label: Additional context
      description: Add any other context, reference issues or screenshots you want to add
    validations:
      required: false
  - type: textarea
    id: pointsOfContact
    attributes:
      label: Points of Contact
      description: People that should have answers (or where to find answers) for any follow-up questions.
      value: |
        | Role | Contact
        | ---- | ----
        | ROLE_NAME | CONTACT_NAME
        | ROLE_NAME | CONTACT_NAME
    validations:
      required: false
  - type: input
    id: neededBy
    attributes:
      label: Needed By
      description: |
        Ideally a date or a target release; helps with prioritization.
        NOTES:
        - The more vague the needed by date is, the more likely it is to get bumped for higher priority issues.
        - Ideal notice is at least two weeks from needed by date; more time is always appreciated.
    validations:
      required: true
  - type: textarea
    id: mentions
    attributes:
      label: Mentions
      description: Additional users to be included e.g @<!-- -->username
      value: |
        Assignees: @WebGIS/ago-azure-devops
    validations:
      required: false
