name: A workflow for my Hello World file
on : 
  workflow_dispatch :
    inputs:
      version:
        description: 'Application Version'     
        required: true
jobs:
  build:
    strategy:
      matrix:
        region_matrix: ['scus','eus']
        app_matrix: ['csm','pub']
      fail-fast: false
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - id: matrix-status
        name: matrix status
        shell: pwsh
        run: |
          Write-Host "App - ${{ matrix.app_matrix }} and region ${{ matrix.region_matrix }}"
          Write-Host "appname="${{matrix.app_matrix}}" >> $GITHUB_OUTPUT
          Write-Host "region="${{matrix.region_matrix}}" >> $GITHUB_OUTPUT
    outputs:
      app_output: ${{ steps.matrix-status.outputs.appname }}
      region_output: ${{ steps.matrix-status.outputs.region }}
  report:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:  
      - name: report
        id: report
        shell: pwsh
        run: |
          Write-Host ${{ needs.build.outputs.app_output }}
          Write-Host ${{ needs.build.outputs.region_output }}
