name: A workflow for my Hello World file
on : 
  workflow_dispatch :
    inputs:
      regions:
        description: 'Azure regions'     
        required: true
        default: "scus,eus"
      apps:
        description: 'Application names'     
        required: true
        default: "csm,pub"
jobs:
  build:
    strategy:
      matrix:
        region_matrix: ['scus','eus']
        app_matrix: ['csm','pub']
      fail-fast: false
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - id: matrix-status
        name: matrix status
        run: |
          echo "${{ matrix.app_matrix }}_${{matrix.region_matrix}}='failure'" >> $GITHUB_OUTPUT
    outputs:
      ${{ matrix.app_matrix }}_${{matrix.region_matrix}}: ${{ matrix.app_matrix }}_${{matrix.region_matrix}}
  report:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:  
      - name: report
        id: report
        shell: pwsh
        run: |
          foreach($region in $regions.split(',')){
            foreach($app in $apps.split(',')){
              Write-Host ${{ needs.build.outputs.$app_$region }}
            }
          }
          
